# Generated by Django 4.2.2 on 2023-06-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercato', '0002_alter_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='formation/')),
            ],
        ),
    ]
