# Generated by Django 4.1.7 on 2023-06-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercato', '0005_role_img'),
        ('mercato', '0005_team_composition'),
    ]

    operations = [
    ]
