# Generated by Django 4.2.2 on 2023-06-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercato', '0005_role_img'),
        ('mercato', '0005_team_composition'),
    ]

    operations = [
    ]
